- name: upgrade web packages slackware
  slackpkg:
    name: mysql,php
    state: latest
    update_cache: true
  become: true
  when:
    - ansible_hostname in groups['slackware']
    - ansible_hostname in groups['http']
  notify:
    - restart mysql
    - restart php
- name: upgrade web packages debian
  apt:
    name: nginx,php,mysql
    state: latest
  become: true
  when:
    - ansible_hostname in groups['debian']
    - ansible_hostname in groups['http']
