- name: install wp-cli
  get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "/usr/bin/wp"
    mode: "u=rwx,g=rx,o=rx"
    force: no
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['wordpress']
- name: update wp-cli
  command: wp cli update
  become: true
  register: result
  changed_when: '"WP-CLI is at the latest version." not in result.stdout'
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['wordpress']
- name: install json debian
  npm:
    name: json
    state: latest
    global: true
  become: true
  when:
    - ansible_hostname in groups['debian']
- name: fetch wordpress plug-ins
  shell: "cat /etc/pyvhost/wordpress | grep -o '/home/[^ ]\\+'"
  register: wordpress_installations
  changed_when: False
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['wordpress']
- name: manage wordpress settings
  shell: "sudo -u $(stat -c %U .) -- sh -c 'wp option get {{ item[1].option }} | {{ item[1].edit }} | wp option update {{ item[1].option }}'"
  args:
    chdir: "{{ item[0] }}"
  become: true
  register: result
  changed_when: '"Success: Updated" in result.stdout'
  when:
    - ansible_hostname in groups['debian']
    - ansible_hostname in groups['wordpress']
  with_nested:
    - "{{ wordpress_installations.stdout_lines }}"
    - - {
        'option': "itsec_file_change --format=json",
        'edit': 'json -e "this.enabled = false"'}
- name: fetch wordpress plug-ins
  shell: "cat /etc/pyvhost/wordpress | grep -o '/home/[^ ]\\+'"
  register: wordpress_installations
  changed_when: False
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['wordpress']
- name: update wordpress
  shell: "sudo -u $(stat -c %U .) -- wp {{ item[1].command }}"
  args:
    chdir: "{{ item[0] }}"
  become: true
  register: result
  changed_when: item[1].unchanged not in result.stdout
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['wordpress']
  with_nested:
    - "{{ wordpress_installations.stdout_lines }}"
    - - {'command': "core update", 'unchanged': 'WordPress is up to date.'}
      - {'command': "core update-db", 'unchanged': 'database already at latest db version'}
      - {'command': "plugin update --all", 'unchanged': 'Plugin already updated.'}
      - {'command': "theme update --all", 'unchanged': 'Theme already updated.'}
