- name: upgrade python slackware
  slackpkg:
    name: python
    state: latest
    update_cache: true
  become: true
  when:
    - ansible_hostname in groups['slackware']
- name: remove pip packages slackware
  slackpkg:
    name: pip,pysetuptools,python-setuptools
    state: absent
  become: true
  when:
    - ansible_hostname in groups['slackware']
- name: remove pip packages debian
  apt:
    name: python-pip,python-setuptools
    state: absent
  become: true
  when:
    - ansible_hostname in groups['debian']
- name: test if pip is installed
  stat:
    path: "{{ item }}"
  become: true
  register: pip_install
  with_items:
    - /usr/lib64/python2.7/site-packages/pip
    - /usr/local/lib/python2.7/dist-packages/pip
  when:
    - ansible_hostname in groups['slackware']
- name: test if pip working
  command: which pip2
  failed_when: False
  changed_when: False
  register: pip_working
  when:
    - ansible_hostname in groups['unix']
- name: remove broken pip installation
  shell: "rm -r {{ item }}"
  failed_when: False
  register: result
  changed_when: result.rc == 0
  become: true
  with_items:
    - /usr/lib64/python2.7/site-packages/pip
    - /usr/lib64/python2.7/site-packages/pip-[0-9]\+.*.dist-info
    - /usr/lib64/python2.7/site-packages/setuptools
    - /usr/lib64/python2.7/site-packages/setuptools-[0-9]\+.*.dist-info
  when:
    - ansible_hostname in groups['slackware']
    - pip_install.results|sum(attribute='stat.exists') != 0
    - pip_working.rc != 0
- name: transfer pip packages slackware
  copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
  become: true
  with_items:
    - get-pip.py
  when:
    - ansible_hostname in groups['unix']
    - pip_install.results|sum(attribute='stat.exists') == 0 or pip_working.rc != 0
- name: install pip packages
  command: "python2 ~/{{ item }}"
  become: true
  with_items:
    - get-pip.py
  when:
    - ansible_hostname in groups['unix']
    - pip_install.results|sum(attribute='stat.exists') == 0 or pip_working.rc != 0
- name: remove pip package files
  file:
    path: "~/{{ item }}"
    state: absent
  become: true
  with_items:
    - get-pip.py
  when:
    - ansible_hostname in groups['unix']
    - pip_install.results|sum(attribute='stat.exists') == 0 or pip_working.rc != 0
- name: upgrade python packaging tools
  pip:
    name: "{{ item }}"
    state: latest
  become: true
  when:
    - ansible_hostname in groups['unix']
  with_items:
    - pip
    - setuptools
