- name: update zsh slackware
  slackpkg:
    name: zsh
    state: latest
    update_cache: true
  become: true
  when:
    - ansible_hostname in groups['slackware']
- name: create zsh directory
  file:
    path: "/etc/zsh/{{ item }}"
    state: directory
    mode: 0755
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
  with_items:
    - ''
    - 'plugins'
    - 'custom'
    - 'custom/themes'
    - 'custom/plugins'
- name: update zsh plugins
  hg:
    repo: "{{ item.repo }}"
    dest: "/etc/zsh/plugins/{{ item.dest }}"
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
  with_items:
      - {'dest': 'zsh-git-prompt', 'repo': 'git+ssh://git@github.com/olivierverdier/zsh-git-prompt'}
      - {'dest': 'zsh-syntax-highlighting', 'repo': 'git+ssh://git@github.com/zsh-users/zsh-syntax-highlighting'}
      - {'dest': 'oh-my-zsh', 'repo': 'git+ssh://git@github.com/robbyrussell/oh-my-zsh'}
- set_fact:
    zshrc_content: "{{ lookup('template', 'templates/zshrc.j2') }}"
    zshenv_content: "{{ lookup('template', 'templates/zshenv.j2') }}"
- name: write zshrc
  blockinfile:
    dest: "/etc/zsh/zshrc"
    content: '{{ zshrc_content }}'
    state: present
    create: yes
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
- name: write zshenv
  blockinfile:
    dest: "/etc/zsh/zshenv"
    content: '{{ zshenv_content }}'
    state: present
    create: yes
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
- name: write zsh theme
  template:
    src: "{{ item.template }}.j2"
    backup: yes
    dest: "/etc/zsh/{{ item.destination }}/{{ item.template }}"
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
  with_items:
      - {'template': 'nihlaeth.zsh-theme', 'destination': 'custom/themes'}
- name: fix user zsh files
  lineinfile:
    dest: "~/.zsh{{ item[0] }}"
    create: yes
    insertbefore: BOF
    line: "source /etc/zsh/zsh{{ item[0] }}"
    state: present
  become: true
  become_user: "{{ item[1] }}"
  with_nested:
    - - rc
      - env
    - - root
      - nihlaeth
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
