- name: confirmation
  assert:
    that: 'confirm == "yes"'
- name: fetch cron rules
  command: crontab -l
  become: true
  become_user: "{{ item }}"
  register: cron_content
  changed_when: False
  with_items: "{{ managed_users }}"
  when:
    - ansible_hostname in groups['unix']
- name: remove cron rules
  shell: "crontab -l | grep -v '.dotfiles' | crontab -"
  changed_when: true
  become: true
  become_user: "{{ item.0 }}"
  with_together:
    - "{{ managed_users }}"
    - "{{ cron_content.results }}"
  when:
    - ansible_hostname in groups['unix']
    - '".dotfiles" in item.1.stdout'
- name: remove dotfiles
  file:
    name: "~/{{ item.1 }}"
    state: absent
  become: true
  become_user: "{{ item.0 }}"
  with_nested:
    - "{{ managed_users }}"
    - - .ssh/config
      - .vimrc
      - .vim
      - .zshrc
      - .zshenv
      - .screenrc
      - .dotfiles
      - .hgrc
      - .hgignore
  when:
    - ansible_hostname in groups['unix']
- name: remove global configuration
  file:
    name: "/etc/{{ item }}"
    state: absent
  become: true
  when:
    - ansible_hostname in groups['slackware']
  with_items:
    - vim/vimrc
    - zsh/zshrc
    - zsh/zshenv

