- name: create mercurial configuration directory
  file:
    path: /etc/mercurial/hg-plugins
    state: directory
    mode: 0755
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
- name: write mercurial config
  template:
    src: "{{ item }}.j2"
    backup: yes
    dest: "/etc/mercurial/{{ item }}"
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
  with_items:
    - hgignore
    - hgrc
- name: remove mercurial slackware
  slackpkg:
    name: mercurial
    state: absent
  become: true
  when:
    - ansible_hostname in groups['slackware']
- name: remove mercurial debian
  apt:
    name: mercurial
    state: absent
  become: true
  when:
    - ansible_hostname in groups['debian']
- name: install git and subversion slackware
  slackpkg:
    name: git,subversion,icu4c,apr-util,neon,sqlite
    state: present
  become: true
  when:
    - ansible_hostname in groups['slackware']
- name: install git and subversion debian
  apt:
    name: git,subversion,libaprutil1-dev,sqlite,python-subvertpy,hgsubversion
    state: present
  become: true
  when:
    - ansible_hostname in groups['debian']
- name: install git and subversion slackware14.2
  slackpkg:
    name: serf
    state: present
  become: true
  when:
    - ansible_hostname in groups['slackware14.2']
- name: install mercurial
  pip:
    name: mercurial
    state: latest
  become: true
- name: install hg-git
  pip:
    name: hg-git
    state: latest
  become: true
- name: install hgsubversion
  pip:
    name: hgsubversion
    state: latest
  become: true
  when:
    - ansible_hostname not in groups['debian']
- name: install subvertpy
  pip:
    name: subvertpy
    state: latest
  become: true
  when:
    - ansible_hostname not in groups['debian']
- name: fetch mercurial plug-ins
  hg:
    repo: "{{ item.repo }}"
    dest: "/etc/mercurial/hg-plugins/{{ item.dest }}"
  become: true
  when:
    - ansible_hostname in groups['unix']
    - ansible_hostname in groups['mine']
  with_items:
      - {'dest': 'hg-prompt', 'repo': 'http://bitbucket.org/sjl/hg-prompt/'}
